### PR TITLE
Fix bug with Git::SeedsTracks calling the wrong class

### PR DESCRIPTION
**Pull request by kntsoriano**
When I was setting up a fresh repository, I noticed that `Git::SeedsTracks` was calling a non existent class called `Git::FetchTrack`.

### CODE REVIEW

**Comment by ccare** [comment]
Looks fine to me, although presumably we only now seed during dev setup? Or is this production code.

**Comment by kntsoriano** [comment]
@ccare Seeds are only used when setting up development :)

**Comment by kytrinyx** [comment]
Would it be OK if we merge this? I need to seed my local database with tracks when running the ETL from v1 to v2.

**Comment by kytrinyx** [comment]
@iHiD says go for it. So I'm going for it!

**Pull request merged**
